name: MLTB-Workflow Deploy

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  # Change these values if you have forked it for your own works
  GitHubMail: "example@gmail.com"
  GitHubName: "TheFlashSpeedster" 
  Branch: "Mega-Mirror"

jobs:

  
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      

      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${{ secrets.GH_TOKEN}}@github.com/${{ secrets.REPO }} -b ${Branch} source
      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls
      - uses: rokibhasansagar/slimhub_actions@main
      - name: running Docker
        timeout-minutes: 325
        continue-on-error: true
        run: |
          docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} mirror-bot
